using System;
using System.IO;
using System.Net;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using CBDownloader.ViewModels;

namespace CBDownloader.Services
{
    public class ExtensionServerService
    {
        private HttpListener _listener = new();
        private CancellationTokenSource _cts = new();

        public void Start()
        {
            _cts = new CancellationTokenSource();
            _listener = new HttpListener();
            _listener.Prefixes.Add("http://127.0.0.1:44321/api/download/");
            _listener.Start();

            Task.Run(() => ListenAsync(_cts.Token));
        }

        public void Stop()
        {
            _cts?.Cancel();
            _listener?.Stop();
        }

        private async Task ListenAsync(CancellationToken token)
        {
            while (!token.IsCancellationRequested)
            {
                try
                {
                    var context = await _listener.GetContextAsync();
                    
                    // Handle preflight requests (CORS) from the browser extension
                    if (context.Request.HttpMethod == "OPTIONS")
                    {
                        AddCorsHeaders(context.Response);
                        context.Response.StatusCode = 200;
                        context.Response.Close();
                        continue;
                    }

                    if (context.Request.HttpMethod == "POST")
                    {
                        using var reader = new StreamReader(context.Request.InputStream, context.Request.ContentEncoding);
                        var body = await reader.ReadToEndAsync();

                        try
                        {
                            var payload = JsonSerializer.Deserialize<ExtensionPayload>(body, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                            if (payload != null && !string.IsNullOrEmpty(payload.Url))
                            {
                                // Save cookies to youtube_cookies.txt
                                if (payload.Cookies != null && payload.Cookies.Length > 0)
                                {
                                    SaveCookies(payload.Cookies);
                                }

                                AddCorsHeaders(context.Response);
                                context.Response.StatusCode = 200;
                                using var writer = new StreamWriter(context.Response.OutputStream);
                                writer.Write("{\"status\":\"success\"}");
                            }
                            else
                            {
                                context.Response.StatusCode = 400; // Bad Request
                            }
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine("Error parsing payload: " + ex.Message);
                            context.Response.StatusCode = 500;
                        }
                    }
                    else
                    {
                        context.Response.StatusCode = 405; // Method not allowed
                    }

                    context.Response.Close();
                }
                catch (HttpListenerException)
                {
                    // Listener stopped
                }
                catch (Exception)
                {
                    // Other errors
                }
            }
        }

        private void AddCorsHeaders(HttpListenerResponse response)
        {
            response.AppendHeader("Access-Control-Allow-Origin", "*");
            response.AppendHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
            response.AppendHeader("Access-Control-Allow-Headers", "Content-Type");
        }

        private void SaveCookies(ExtensionCookie[] cookies)
        {
            var binFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "CBDownloader", "bin");
            if (!Directory.Exists(binFolder))
            {
                Directory.CreateDirectory(binFolder);
            }

            var txtPath = Path.Combine(binFolder, "youtube_cookies.txt");
            var sb = new StringBuilder();
            sb.AppendLine("# Netscape HTTP Cookie File");
            sb.AppendLine("# This file was generated by CBDownloader Extension");
            sb.AppendLine();

            foreach (var cookie in cookies)
            {
                string domain = cookie.Domain.StartsWith(".") ? cookie.Domain : "." + cookie.Domain;
                string flag = domain.StartsWith(".") ? "TRUE" : "FALSE";
                string path = string.IsNullOrEmpty(cookie.Path) ? "/" : cookie.Path;
                string secure = cookie.Secure ? "TRUE" : "FALSE";

                long expiry = cookie.ExpirationDate > 0 ? (long)cookie.ExpirationDate : DateTimeOffset.UtcNow.AddYears(1).ToUnixTimeSeconds();

                sb.AppendLine($"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{cookie.Name}\t{cookie.Value}");
            }

            File.WriteAllText(txtPath, sb.ToString());
            
            // Force settings update so YoutubeDLService prioritizes the file
            SettingsService.Current.UseBrowserCookies = true;
            SettingsService.Save();
        }

        public class ExtensionPayload
        {
            public string? Url { get; set; }
            public ExtensionCookie[]? Cookies { get; set; }
        }

        public class ExtensionCookie
        {
            public string Domain { get; set; } = string.Empty;
            public string? Path { get; set; }
            public bool Secure { get; set; }
            public double ExpirationDate { get; set; }
            public string Name { get; set; } = string.Empty;
            public string Value { get; set; } = string.Empty;
        }
    }
}
